/** @type {import('tailwindcss').Config} */
// Tokens ported verbatim from the Google Stitch export so the React build
// matches the reference screens (Home, Bill Tracker, Vote Detail, MP Profile).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#e1e0ff',
        'on-secondary': '#ffffff',
        'surface-container': '#efecf8',
        'inverse-primary': '#c0c1ff',
        'surface-dim': '#dbd8e4',
        error: '#ba1a1a',
        background: '#fcf8ff',
        'primary-container': '#6063ee',
        'surface-variant': '#e4e1ed',
        'on-primary-container': '#fffbff',
        'surface-tint': '#494bd6',
        tertiary: '#904900',
        'on-error': '#ffffff',
        surface: '#fcf8ff',
        'inverse-on-surface': '#f2effb',
        'on-secondary-fixed-variant': '#005048',
        'tertiary-fixed-dim': '#ffb783',
        'outline-variant': '#c7c4d7',
        'on-surface': '#1b1b23',
        'on-tertiary-fixed-variant': '#703700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b55d00',
        'tertiary-fixed': '#ffdcc5',
        'surface-bright': '#fcf8ff',
        outline: '#767586',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#2f2ebe',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#303038',
        'on-tertiary-container': '#fffbff',
        secondary: '#006b5f',
        'on-secondary-container': '#006f64',
        'secondary-container': '#6df5e1',
        'on-error-container': '#93000a',
        'secondary-fixed': '#71f8e4',
        'on-surface-variant': '#464554',
        'on-primary-fixed': '#07006c',
        'surface-container-highest': '#e4e1ed',
        'surface-container-high': '#e9e6f3',
        'on-secondary-fixed': '#00201c',
        'secondary-fixed-dim': '#4fdbc8',
        'primary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed': '#301400',
        'on-primary': '#ffffff',
        'on-background': '#1b1b23',
        'surface-container-low': '#f5f2fe',
        primary: '#4648d4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-margin-mobile': '16px',
        'container-margin-desktop': '40px',
        'section-gap': '48px',
        gutter: '16px',
        'stack-gap': '12px',
        unit: '4px',
      },
      fontFamily: {
        'display-lg': ['Montserrat', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      keyframes: {
        pulseDot: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
        slideIn: {
          from: { opacity: '0', transform: 'translateY(20px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        pulseShadow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(70, 72, 212, 0.4)' },
          '50%': { boxShadow: '0 0 0 10px rgba(70, 72, 212, 0)' },
        },
      },
      animation: {
        'pulse-dot': 'pulseDot 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        slide: 'slideIn 0.6s ease-out forwards',
        'pulse-shadow': 'pulseShadow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
    },
  },
  plugins: [],
}
