"""Scrape committee detail pages into src/data/realCommittees.ts.

Member profile IDs on each committee page map directly to roster MP IDs
(mp-<id>), so membership is exact. Downloads the listing + every committee
page itself (cached under tmp/cache).

Run from repo root: python scripts/scrape_committees.py
"""
import re, json, html as ihtml, os
from majlis import BASE, RUN_DATE, fetch

CATEGORIES = [
    "Parliamentary work related Standing Committees",
    "State Institutions related Standing Committees",
    "Select Committees (Completed)",
    "Select Committees",
    "Joint Committees",
]

def clean(s):
    s = ihtml.unescape(s)
    s = s.replace("\xa0", " ").replace("�", "")
    return re.sub(r"\s+", " ", s).strip(" -?")

# id -> (category, name, status) from the listing
listing = fetch(f"{BASE}/committees", refresh=True)
meta = {}
for cid, inner in re.findall(
    r'href="https://majlis\.gov\.mv/en/20-parliament/committee/(\d+)"[^>]*>(.*?)</a>', listing, re.S
):
    if cid in meta:
        continue
    raw = clean(re.sub(r"<[^>]+>", " ", inner))
    category = next((c for c in CATEGORIES if raw.startswith(c)), "")
    name = raw[len(category):].strip() if category else raw
    status = "Completed" if name.endswith("Completed") or "(Completed)" in category else "Ongoing"
    name = re.sub(r"\s*(Ongoing|Completed)\s*$", "", name).strip()
    meta[cid] = (category, name, status)

def section_pos(h, label):
    m = re.search(re.escape(label), h)
    return m.start() if m else None

def member_ids_between(h, lo, hi):
    out = []
    for m in re.finditer(r"/20-parliament/members/(\d+)", h):
        if (lo is None or m.start() >= lo) and (hi is None or m.start() < hi):
            if m.group(1) not in out:
                out.append(m.group(1))
    return out

def first_member_after(h, label):
    p = section_pos(h, label)
    if p is None:
        return None
    m = re.search(r"/20-parliament/members/(\d+)", h[p:])
    return m.group(1) if m else None

records = []
for cid in sorted(meta, key=int):
    h = fetch(f"{BASE}/committee/{cid}", refresh=True)
    category, lname, status = meta[cid]
    # name: first <h3> on the page (strip "20th" prefix); fall back to listing name
    h3s = [clean(re.sub(r"<[^>]+>", " ", m.group(1))) for m in re.finditer(r"<h3[^>]*>(.*?)</h3>", h, re.S)]
    name = next((re.sub(r"^20th\s*", "", x).strip() for x in h3s if "Committee" in x and "Members" not in x and "Documents" not in x and "Works" not in x and "Meetings" not in x), "")
    if not name:
        name = lname
    p_members = section_pos(h, "Committee Members")
    p_former = section_pos(h, "Former members")
    p_docs = section_pos(h, "Committee Documents")
    p_meet = section_pos(h, "Committee Meetings")
    p_works = section_pos(h, "Committee Works")
    end_current = p_former or p_docs or p_meet
    current = member_ids_between(h, p_members, end_current)
    former = member_ids_between(h, p_former, p_docs or p_meet) if p_former else []
    former = [x for x in former if x not in current]
    chair = first_member_after(h, "Chairperson")
    vice = first_member_after(h, "Vice Chairperson")
    # meeting dates within the meetings section
    meet_html = h[p_meet:(p_works or len(h))] if p_meet else ""
    dates = re.findall(r"\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4}", meet_html)
    seen = set(); dates = [d for d in dates if not (d in seen or seen.add(d))]
    works_html = h[p_works:] if p_works else ""
    works = len(set(re.findall(r"/20-parliament/parliament-work/(\d+)", works_html)))
    # documents (attendance reports etc.) in the "Committee Documents" section, downloaded to tmp/docs
    docs_html = h[p_docs:(p_meet or p_works or len(h))] if p_docs else ""
    documents = []
    for k, m in enumerate(re.finditer(r'<a[^>]+href="(https://majlis\.gov\.mv/storage/[^"]+)"[^>]*>(.*?)</a>', docs_html, re.S), 1):
        url = m.group(1)
        if any(d["url"] == url for d in documents):
            continue
        path = os.path.join("tmp", "docs", f"cmt-{cid}-{k}.pdf")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        if not os.path.exists(path):
            open(path, "wb").write(fetch(url, binary=True))
        documents.append({"label": clean(re.sub(r"<[^>]+>", " ", m.group(2))), "url": url, "file": path.replace("\\", "/")})
    records.append({
        "id": cid, "name": name, "category": category or "Committee", "status": status,
        "chairId": chair, "viceChairId": vice,
        "memberIds": current, "formerMemberIds": former,
        "meetingDates": dates, "works": works, "documents": documents,
        "url": f"https://majlis.gov.mv/en/20-parliament/committee/{cid}",
        "fetchedAt": RUN_DATE,
    })
    print(f"{cid:>4} | {name[:46]:46} | members {len(current):2d} former {len(former):2d} "
          f"meetings {len(dates):2d} works {works:2d} docs {len(documents)} chair {chair}")

ts = ("// AUTO-GENERATED by scripts/scrape_committees.py from majlis.gov.mv committee pages.\n"
      "// Member IDs map directly to roster MP ids (mp-<id>).\n\n"
      "export interface RealCommittee {\n"
      "  id: string; name: string; category: string; status: 'Ongoing' | 'Completed'\n"
      "  chairId: string | null; viceChairId: string | null\n"
      "  memberIds: string[]; formerMemberIds: string[]\n"
      "  meetingDates: string[]; works: number; url: string; fetchedAt: string\n"
      "  documents: { label: string; url: string; file: string }[]\n}\n\n"
      "export const REAL_COMMITTEES: RealCommittee[] = " +
      json.dumps(records, indent=2, ensure_ascii=False).replace('"chairId": null', '"chairId": null') +
      "\n")
open("src/data/realCommittees.ts", "w", encoding="utf-8", newline="\n").write(ts)
print("\nwrote src/data/realCommittees.ts with", len(records), "committees")
