"""Scrape committee detail pages into src/data/realCommittees.ts.

Member profile IDs on each committee page map directly to roster MP IDs
(mp-<id>), so membership is exact. Run from repo root after the committee
pages are downloaded into tmp/ (see the shell step in the session).
"""
import re, json, html as ihtml, glob, os

CATEGORIES = [
    "Parliamentary work related Standing Committees",
    "State Institutions related Standing Committees",
    "Select Committees (Completed)",
    "Select Committees",
    "Joint Committees",
]

def clean(s):
    s = ihtml.unescape(s)
    s = s.replace("\xa0", " ").replace("�", "")
    return re.sub(r"\s+", " ", s).strip(" -?")

# id -> (category, name, status) from the listing
listing = open("tmp/committees.html", encoding="utf-8", errors="ignore").read()
meta = {}
for cid, inner in re.findall(
    r'href="https://majlis\.gov\.mv/en/20-parliament/committee/(\d+)"[^>]*>(.*?)</a>', listing, re.S
):
    if cid in meta:
        continue
    raw = clean(re.sub(r"<[^>]+>", " ", inner))
    category = next((c for c in CATEGORIES if raw.startswith(c)), "")
    name = raw[len(category):].strip() if category else raw
    status = "Completed" if name.endswith("Completed") or "(Completed)" in category else "Ongoing"
    name = re.sub(r"\s*(Ongoing|Completed)\s*$", "", name).strip()
    meta[cid] = (category, name, status)

def section_pos(h, label):
    m = re.search(re.escape(label), h)
    return m.start() if m else None

def member_ids_between(h, lo, hi):
    out = []
    for m in re.finditer(r"/20-parliament/members/(\d+)", h):
        if (lo is None or m.start() >= lo) and (hi is None or m.start() < hi):
            if m.group(1) not in out:
                out.append(m.group(1))
    return out

def first_member_after(h, label):
    p = section_pos(h, label)
    if p is None:
        return None
    m = re.search(r"/20-parliament/members/(\d+)", h[p:])
    return m.group(1) if m else None

records = []
paths = [p for p in glob.glob("tmp/c*.html") if re.search(r"[/\\]c\d+\.html$", p)]
for path in sorted(paths, key=lambda p: int(re.search(r"c(\d+)\.html$", p).group(1))):
    cid = re.search(r"c(\d+)\.html$", path).group(1)
    if cid not in meta:
        continue
    h = open(path, encoding="utf-8", errors="ignore").read()
    category, lname, status = meta[cid]
    # name: first <h3> on the page (strip "20th" prefix); fall back to listing name
    h3s = [clean(re.sub(r"<[^>]+>", " ", m.group(1))) for m in re.finditer(r"<h3[^>]*>(.*?)</h3>", h, re.S)]
    name = next((re.sub(r"^20th\s*", "", x).strip() for x in h3s if "Committee" in x and "Members" not in x and "Documents" not in x and "Works" not in x and "Meetings" not in x), "")
    if not name:
        name = lname
    p_members = section_pos(h, "Committee Members")
    p_former = section_pos(h, "Former members")
    p_docs = section_pos(h, "Committee Documents")
    p_meet = section_pos(h, "Committee Meetings")
    p_works = section_pos(h, "Committee Works")
    end_current = p_former or p_docs or p_meet
    current = member_ids_between(h, p_members, end_current)
    former = member_ids_between(h, p_former, p_docs or p_meet) if p_former else []
    former = [x for x in former if x not in current]
    chair = first_member_after(h, "Chairperson")
    vice = first_member_after(h, "Vice Chairperson")
    # meeting dates within the meetings section
    meet_html = h[p_meet:(p_works or len(h))] if p_meet else ""
    dates = re.findall(r"\d{1,2}\s+(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{4}", meet_html)
    seen = set(); dates = [d for d in dates if not (d in seen or seen.add(d))]
    works_html = h[p_works:] if p_works else ""
    works = len(set(re.findall(r"/20-parliament/parliament-work/(\d+)", works_html)))
    records.append({
        "id": cid, "name": name, "category": category or "Committee", "status": status,
        "chairId": chair, "viceChairId": vice,
        "memberIds": current, "formerMemberIds": former,
        "meetingDates": dates, "works": works,
        "url": f"https://majlis.gov.mv/en/20-parliament/committee/{cid}",
    })
    print(f"{cid:>4} | {name[:46]:46} | members {len(current):2d} former {len(former):2d} "
          f"meetings {len(dates):2d} works {works:2d} chair {chair}")

ts = ("// AUTO-GENERATED by scripts/scrape_committees.py from majlis.gov.mv committee pages.\n"
      "// Member IDs map directly to roster MP ids (mp-<id>).\n\n"
      "export interface RealCommittee {\n"
      "  id: string; name: string; category: string; status: 'Ongoing' | 'Completed'\n"
      "  chairId: string | null; viceChairId: string | null\n"
      "  memberIds: string[]; formerMemberIds: string[]\n"
      "  meetingDates: string[]; works: number; url: string\n}\n\n"
      "export const REAL_COMMITTEES: RealCommittee[] = " +
      json.dumps(records, indent=2, ensure_ascii=False).replace('"chairId": null', '"chairId": null') +
      "\n")
open("src/data/realCommittees.ts", "w", encoding="utf-8").write(ts)
print("\nwrote src/data/realCommittees.ts with", len(records), "committees")
