// AUTO-GENERATED by scripts/scrape_committees.py from majlis.gov.mv committee pages.
// Member IDs map directly to roster MP ids (mp-<id>).

export interface RealCommittee {
  id: string; name: string; category: string; status: 'Ongoing' | 'Completed'
  chairId: string | null; viceChairId: string | null
  memberIds: string[]; formerMemberIds: string[]
  meetingDates: string[]; works: number; url: string; fetchedAt: string
  documents: { label: string; url: string; file: string }[]
}

export const REAL_COMMITTEES: RealCommittee[] = [
  {
    "id": "115",
    "name": "General Purpose Committee",
    "category": "Parliamentary work related Standing Committees",
    "status": "Ongoing",
    "chairId": "210",
    "viceChairId": "180",
    "memberIds": [
      "244",
      "210",
      "180",
      "211",
      "213",
      "216",
      "225",
      "239",
      "251",
      "255",
      "203"
    ],
    "formerMemberIds": [
      "260"
    ],
    "meetingDates": [
      "22 Aug 2026",
      "18 Aug 2026",
      "17 Aug 2026",
      "16 Aug 2026",
      "10 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "General Purpose Committee's Attendance report till August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/115/wXkPned6hTcVTjIdRxPommSPlKoGqwK1ICngTwfV.pdf",
        "file": "tmp/docs/cmt-115-1.pdf"
      },
      {
        "label": "General Purpose Committee's Attendance report till August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/115/EHLpmzgOmlHoesBtV80MTIfl7nNfZOGoMxi8czpQ.xlsx",
        "file": "tmp/docs/cmt-115-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/115",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "116",
    "name": "Petition Committee",
    "category": "Parliamentary work related Standing Committees",
    "status": "Ongoing",
    "chairId": "195",
    "viceChairId": "198",
    "memberIds": [
      "256",
      "195",
      "198",
      "199",
      "212",
      "220",
      "261",
      "246",
      "231",
      "240"
    ],
    "formerMemberIds": [
      "178",
      "205",
      "206",
      "250",
      "209"
    ],
    "meetingDates": [
      "22 Aug 2026",
      "16 Aug 2026",
      "10 Aug 2026",
      "28 Jul 2026",
      "23 Jun 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Petition Committee's Attendance report up to 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/116/zSnI6snWZJNqalt83DxD6wz4Y7jnHxRGXUhAv5u0.xlsx",
        "file": "tmp/docs/cmt-116-1.pdf"
      },
      {
        "label": "Petition Committee's Attendance report up to 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/116/yBlkY1Ark5QKJYM8rkuu29MmXlE83Hlth9jQKJdI.pdf",
        "file": "tmp/docs/cmt-116-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/116",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "117",
    "name": "Committee on Member’s Privileges and Ethics",
    "category": "Parliamentary work related Standing Committees",
    "status": "Ongoing",
    "chairId": "175",
    "viceChairId": "179",
    "memberIds": [
      "195",
      "175",
      "179",
      "202",
      "204",
      "215",
      "243",
      "253",
      "260",
      "261",
      "231"
    ],
    "formerMemberIds": [
      "191",
      "203"
    ],
    "meetingDates": [
      "04 Aug 2026",
      "28 Jul 2026",
      "23 Jun 2026",
      "06 May 2026",
      "15 Apr 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Committee on Member’s Privileges and Ethics till 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/117/U7zuKbagxrUJ0oMAkbDOD0Zj0L91wQ5jyO1coRyC.xlsx",
        "file": "tmp/docs/cmt-117-1.pdf"
      },
      {
        "label": "Attendance Report of Committee on Member’s Privileges and Ethics till 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/117/mese4tUYAOapulbzVqi2LeWtbx7z51JTwaoOIIAo.pdf",
        "file": "tmp/docs/cmt-117-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/117",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "118",
    "name": "Committee on Secondary Legislation",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "227",
    "viceChairId": "182",
    "memberIds": [
      "224",
      "227",
      "182",
      "193",
      "200",
      "208",
      "209",
      "210",
      "250",
      "255",
      "257"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "12 Aug 2026",
      "14 Jul 2026",
      "23 Jun 2026",
      "05 May 2026",
      "13 Apr 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on Secondary Legislation's Attendance Report till August 2026 (20th majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/118/6NDjIgfyDwKlIURjINAd1NN8JvfW3g0H0wVuOGzu.xlsx",
        "file": "tmp/docs/cmt-118-1.pdf"
      },
      {
        "label": "Committee on Secondary Legislation's Attendance Report till August 2026 (20th majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/118/mAKJ3T4v50CCryU9FMjfc5kvFuzVawLh7OSIYJCc.pdf",
        "file": "tmp/docs/cmt-118-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/118",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "119",
    "name": "Public Accounts Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "217",
    "viceChairId": "177",
    "memberIds": [
      "232",
      "217",
      "177",
      "196",
      "197",
      "206",
      "231",
      "252",
      "266",
      "254",
      "185"
    ],
    "formerMemberIds": [
      "240",
      "178",
      "194"
    ],
    "meetingDates": [
      "19 Aug 2026",
      "16 Aug 2026",
      "13 Aug 2026",
      "12 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Public Accounts Committee and sub-committees till 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/119/qnqoHidpoDck1Xq9eOk65Z4FGAMnvySeFwD8hVPM.xlsx",
        "file": "tmp/docs/cmt-119-1.pdf"
      },
      {
        "label": "Attendance Report of Public Accounts Committee and sub-committees till 31st August2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/119/D2ae0Oui9eVsvlNFMP5vLbSfLOEu7WmpbOpkDfdd.pdf",
        "file": "tmp/docs/cmt-119-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/119",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "120",
    "name": "Committee on Economic Affairs",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "265",
    "viceChairId": "185",
    "memberIds": [
      "249",
      "265",
      "185",
      "203",
      "218",
      "229",
      "222",
      "209",
      "258",
      "206",
      "242"
    ],
    "formerMemberIds": [
      "192",
      "207",
      "246",
      "223",
      "199",
      "237",
      "239"
    ],
    "meetingDates": [
      "06 Oct 2026",
      "25 Aug 2026",
      "23 Aug 2026",
      "18 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on Economic Affairs' Attendance report up to 30th September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/120/NCBulgD8j9cfk03M95D2QA7Sp2sD0b0utNafV5dS.xlsx",
        "file": "tmp/docs/cmt-120-1.pdf"
      },
      {
        "label": "Committee on Economic Affairs' Attendance report up to 30th September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/120/8irORl3NBvQ1xxhe8EPVGDWy9KcHFzywl9OPcZZW.pdf",
        "file": "tmp/docs/cmt-120-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/120",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "121",
    "name": "Committee on Social Affairs",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "190",
    "viceChairId": "186",
    "memberIds": [
      "188",
      "190",
      "186",
      "205",
      "221",
      "223",
      "226",
      "245",
      "263",
      "264",
      "182"
    ],
    "formerMemberIds": [
      "218",
      "213"
    ],
    "meetingDates": [
      "18 Aug 2026",
      "17 Aug 2026",
      "16 Aug 2026",
      "01 Jul 2026",
      "24 Jun 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on Social Affairs' Attendance report up to July 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/121/27jhnvrk3DnS4llQAoTm8KrR01PXZJqbw8plqqhF.xlsx",
        "file": "tmp/docs/cmt-121-1.pdf"
      },
      {
        "label": "Committee on Social Affairs' Attendance report up to July 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/121/vYgtRiN25Fypd00k8OJXDHt8vHcyEfZPCuTMjkaC.pdf",
        "file": "tmp/docs/cmt-121-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/121",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "122",
    "name": "Committee on National Security Services (241)",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "214",
    "viceChairId": "187",
    "memberIds": [
      "217",
      "214",
      "187",
      "196",
      "197",
      "216",
      "231",
      "232",
      "234",
      "244",
      "246",
      "223",
      "252"
    ],
    "formerMemberIds": [
      "240",
      "222",
      "191"
    ],
    "meetingDates": [
      "12 Aug 2026",
      "28 Jul 2026",
      "29 Jun 2026",
      "06 May 2026",
      "21 Apr 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on National Security Services Attendance report - up to 31 July 2026",
        "url": "https://majlis.gov.mv/storage/committee_files/122/jUvJzWouoQyy4BeMRCN5SmHQFDa3m7QYnlay44V5.xlsx",
        "file": "tmp/docs/cmt-122-1.pdf"
      },
      {
        "label": "Committee on National Security Services Attendance report - up to 31 July 2026",
        "url": "https://majlis.gov.mv/storage/committee_files/122/VqqSreAEMAv3UflkXTbay6GduuekdqLmf2oLJpCS.pdf",
        "file": "tmp/docs/cmt-122-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/122",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "123",
    "name": "Committee on Independent Institutions",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "196",
    "viceChairId": "181",
    "memberIds": [
      "225",
      "196",
      "181",
      "183",
      "187",
      "247",
      "267",
      "194",
      "195",
      "258"
    ],
    "formerMemberIds": [
      "224",
      "233",
      "236",
      "241",
      "206",
      "254",
      "179",
      "177"
    ],
    "meetingDates": [
      "07 Oct 2026",
      "24 Aug 2026",
      "23 Aug 2026",
      "17 Aug 2026",
      "15 Jul 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on Independent Institutions Attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/123/bxoX5NeSOh4yzlvwkkbTIWSmlu2hnp96VEfzmg9s.xlsx",
        "file": "tmp/docs/cmt-123-1.pdf"
      },
      {
        "label": "Committee on Independent Institutions Attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/123/ZvCuCWJ6YJBu8jEF2BAazgBbXNVaUqsVpOoIctij.pdf",
        "file": "tmp/docs/cmt-123-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/123",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "124",
    "name": "Government Oversight Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "236",
    "viceChairId": "177",
    "memberIds": [
      "191",
      "236",
      "177",
      "181",
      "183",
      "186",
      "193",
      "195",
      "246",
      "249",
      "235"
    ],
    "formerMemberIds": [
      "264",
      "250"
    ],
    "meetingDates": [
      "29 Jul 2026",
      "22 Jun 2026",
      "13 May 2026",
      "27 Apr 2026",
      "11 Feb 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Government Oversight Committee's Attendance report up to 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/124/cifCxWbihFxowBtre5VKOgSzIojEFCSJqbwo0LRt.xlsx",
        "file": "tmp/docs/cmt-124-1.pdf"
      },
      {
        "label": "Government Oversight Committee's Attendance report up to 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/124/JxdSy0nvmq0Aq0a3NU2Ge4VjJIve70FTtXXE6My6.pdf",
        "file": "tmp/docs/cmt-124-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/124",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "125",
    "name": "Committee on National Development And Heritage",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "192",
    "viceChairId": "176",
    "memberIds": [
      "194",
      "192",
      "176",
      "216",
      "230",
      "252",
      "255",
      "265",
      "179",
      "206",
      "250"
    ],
    "formerMemberIds": [
      "184",
      "239",
      "262",
      "248"
    ],
    "meetingDates": [
      "25 Aug 2026",
      "24 Aug 2026",
      "23 Aug 2026",
      "22 Aug 2026",
      "18 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on National Development and Heritage attendance report - Up to August 2026",
        "url": "https://majlis.gov.mv/storage/committee_files/125/mV3RNGRKrWJzN3SFmWnwgVvNUKXD1h68lOgEW9Jp.xlsx",
        "file": "tmp/docs/cmt-125-1.pdf"
      },
      {
        "label": "Committee on National Development and Heritage attendance report - Up to August 2026",
        "url": "https://majlis.gov.mv/storage/committee_files/125/tbZqrVjQ07ITR9kUwHwakwDVfZe8X1fsFNlgLivr.pdf",
        "file": "tmp/docs/cmt-125-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/125",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "126",
    "name": "Foreign Relations Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "200",
    "viceChairId": "184",
    "memberIds": [
      "228",
      "200",
      "184",
      "199",
      "207",
      "220",
      "237",
      "247",
      "254",
      "262",
      "189"
    ],
    "formerMemberIds": [
      "176"
    ],
    "meetingDates": [
      "23 Aug 2026",
      "16 Aug 2026",
      "12 Aug 2026",
      "04 Aug 2026",
      "03 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Foreign Relations Committee's Attendance report up to 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/126/PoV8wu5bnxJDYmM2TsGwlPaOaKDn7eLjoAOkodZe.xlsx",
        "file": "tmp/docs/cmt-126-1.pdf"
      },
      {
        "label": "Foreign Relations Committee's Attendance report up to 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/126/yNQi3gpNkiBlpLl5Wf4iy5cS9QL2ORqLgZY67yFg.pdf",
        "file": "tmp/docs/cmt-126-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/126",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "127",
    "name": "Committee on Decentralization",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "250",
    "viceChairId": "178",
    "memberIds": [
      "185",
      "250",
      "178",
      "212",
      "221",
      "226",
      "238",
      "243",
      "245",
      "267",
      "218"
    ],
    "formerMemberIds": [
      "268",
      "266"
    ],
    "meetingDates": [
      "24 Aug 2026",
      "23 Aug 2026",
      "17 Aug 2026",
      "16 Aug 2026",
      "11 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on Decentralization's attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/127/8i5rqwqlp5l5dS4JwZsB1nRfkYGbWZZrIBxKlOS3.pdf",
        "file": "tmp/docs/cmt-127-1.pdf"
      },
      {
        "label": "Committee on Decentralization's attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/127/zitClDzqEvPyNUXzGcdd6kxcceQh04TXHM9pGrGS.xlsx",
        "file": "tmp/docs/cmt-127-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/127",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "128",
    "name": "Judiciary Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "206",
    "viceChairId": "218",
    "memberIds": [
      "210",
      "206",
      "218",
      "222",
      "229",
      "242",
      "251",
      "204",
      "244",
      "258",
      "250"
    ],
    "formerMemberIds": [
      "208",
      "227",
      "249",
      "224",
      "182",
      "215",
      "267",
      "199",
      "203"
    ],
    "meetingDates": [
      "11 Aug 2026",
      "29 Jul 2026",
      "23 Jun 2026",
      "11 May 2026",
      "21 Apr 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Judiciary Committee Attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/128/XVz0I0HJzC7beTAyjTi2oFzyxqgyJPhsVzBrvFdj.xlsx",
        "file": "tmp/docs/cmt-128-1.pdf"
      },
      {
        "label": "Judiciary Committee Attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/128/iC7Lu9VRCwcXdmW8FHmhnQE4UCZ4YmU3EyzO0X2B.pdf",
        "file": "tmp/docs/cmt-128-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/128",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "129",
    "name": "Committee on Environment and Climate Change",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "241",
    "viceChairId": "190",
    "memberIds": [
      "189",
      "241",
      "190",
      "219",
      "228",
      "238",
      "250",
      "263",
      "266",
      "176",
      "268"
    ],
    "formerMemberIds": [
      "198",
      "206",
      "240"
    ],
    "meetingDates": [
      "11 Aug 2026",
      "10 Aug 2026",
      "05 Aug 2026",
      "03 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of the Committee on Environment and Climate Change up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/129/blFSaXwtmVbQu6HP3a6XiZLedI2AZvswTcQs6K4y.pdf",
        "file": "tmp/docs/cmt-129-1.pdf"
      },
      {
        "label": "Attendance Report of the Committee on Environment and Climate Change up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/129/0jo51dWk4Ab8rTYaw0ZkLRI0WRewjmC5ZgcSn7Ss.xlsx",
        "file": "tmp/docs/cmt-129-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/129",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "130",
    "name": "Committee on Human Rights and Gender",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "248",
    "viceChairId": "179",
    "memberIds": [
      "245",
      "248",
      "179",
      "199",
      "201",
      "227",
      "232",
      "254",
      "264",
      "189",
      "220"
    ],
    "formerMemberIds": [
      "213",
      "235",
      "256",
      "188",
      "206"
    ],
    "meetingDates": [
      "06 Oct 2026",
      "19 Aug 2026",
      "16 Aug 2026",
      "12 Aug 2026",
      "11 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Human Rights and Gender Committee's Attendance Report till August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/130/20AVImo9rEXfm5t8oZeWTc5QtW8MSh27J8L5jUno.pdf",
        "file": "tmp/docs/cmt-130-1.pdf"
      },
      {
        "label": "Human Rights and Gender Committee's Attendance Report till August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/130/x4RInLw9A00z1svSgPddssK9dvwKJE5yeifdSHi3.xlsx",
        "file": "tmp/docs/cmt-130-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/130",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "131",
    "name": "Committee on State Owned Enterprises",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "247",
    "viceChairId": "187",
    "memberIds": [
      "239",
      "247",
      "187",
      "230",
      "253",
      "256",
      "257",
      "258",
      "260",
      "193",
      "205"
    ],
    "formerMemberIds": [
      "240",
      "194"
    ],
    "meetingDates": [
      "11 Aug 2026",
      "03 Aug 2026",
      "07 Jul 2026",
      "01 Jul 2026",
      "23 Jun 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on State Owned Enterprises and it's Sub-Committee's Attendance Report till September 2026 (20th majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/131/O0oaO2IcYN2ULskwfo1lPIkDRjOdUQ5R0F2BGT74.pdf",
        "file": "tmp/docs/cmt-131-1.pdf"
      },
      {
        "label": "Committee on State Owned Enterprises and it's Sub-Committee's Attendance Report till September 2026 (20th majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/131/nz5BsouCTjWyQV3vVI6kgmf69cO6r997QW7B9MPI.xlsx",
        "file": "tmp/docs/cmt-131-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/131",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "132",
    "name": "Committee on Information and Communication Technology",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "184",
    "viceChairId": "175",
    "memberIds": [
      "204",
      "184",
      "175",
      "180",
      "201",
      "202",
      "211",
      "215",
      "219",
      "235",
      "237"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "06 Oct 2026",
      "18 Aug 2026",
      "17 Aug 2026",
      "12 Aug 2026",
      "11 Aug 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Information and Communication Technology Committee's Attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/132/tqZOip6WHC3kQ0H8wNkjCWsWlCh1nFIxlujwZszY.xlsx",
        "file": "tmp/docs/cmt-132-1.pdf"
      },
      {
        "label": "Information and Communication Technology Committee's Attendance report up to August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/132/wfW7phzknUkHVistQNg8x8bsfUM7dNGT3ik306TC.pdf",
        "file": "tmp/docs/cmt-132-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/132",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "133",
    "name": "Foreign Relations Sub Committee (To review Annual Reports)",
    "category": "Select Committees",
    "status": "Completed",
    "chairId": "247",
    "viceChairId": "184",
    "memberIds": [
      "228",
      "247",
      "184",
      "199",
      "200",
      "207",
      "237"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "13 Aug 2024",
      "06 Aug 2024",
      "30 Jul 2024",
      "09 Jul 2024",
      "11 Jun 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Foreign Relations Committee's Sub Committee 1 Attendance Report up to August 2024",
        "url": "https://majlis.gov.mv/storage/committee_files/133/2MOlgOGQdO5KMcmfDt7GQy6AK2Q45RALbGYVH1ep.pdf",
        "file": "tmp/docs/cmt-133-1.pdf"
      },
      {
        "label": "Foreign Relations Committee's Sub Committee 1 Attendance Report up to August 2024",
        "url": "https://majlis.gov.mv/storage/committee_files/133/MydvV1E4gy85iB2pFn5Dt5pwq9marmCmosZEw2jp.xlsx",
        "file": "tmp/docs/cmt-133-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/133",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "134",
    "name": "Public Accounts Committee's Sub Committee - 01 (To review Audit Reports)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "196",
    "viceChairId": "197",
    "memberIds": [
      "206",
      "196",
      "197",
      "231",
      "266"
    ],
    "formerMemberIds": [
      "178"
    ],
    "meetingDates": [
      "13 Aug 2025",
      "12 Aug 2025",
      "17 Jun 2025",
      "30 Apr 2025",
      "19 Mar 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 1 of Public Accounts Committee till 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/134/gPSMCZQZZWpye6ushdXoeh9ikJClpYzoYdGyByBf.xlsx",
        "file": "tmp/docs/cmt-134-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 1 of Public Accounts Committee till 31st August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/134/aCQIBbzUlTlWzxLvlmXpHLoXgVS0JTM4BLaHtk3r.pdf",
        "file": "tmp/docs/cmt-134-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/134",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "135",
    "name": "State Owned Enterprises Committee's Sub-Committee 4 (To review the status of state-owned enterprises in the bank and finance sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "253",
    "viceChairId": "257",
    "memberIds": [
      "230",
      "253",
      "257",
      "258"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "22 Jul 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 4 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/135/nKPodHwXil2hHEZ8kz9jsW4aUFhMHCuGGwiJuOeP.pdf",
        "file": "tmp/docs/cmt-135-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 4 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/135/awOyLvbxWHyTqDJRpf6SzR1g1fHoYiRc8SmPXl4D.xlsx",
        "file": "tmp/docs/cmt-135-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/135",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "136",
    "name": "State Owned Enterprises Committee's Sub-Committee 6 (To review the status of state-owned enterprises in the utilities sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "253",
    "viceChairId": "253",
    "memberIds": [
      "260",
      "253",
      "256"
    ],
    "formerMemberIds": [
      "240"
    ],
    "meetingDates": [
      "27 Nov 2024",
      "30 Jul 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 6 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/136/8zdINusmhwGufpSnh8aWqjhQo8PB6elaTS69XOmU.pdf",
        "file": "tmp/docs/cmt-136-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 6 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/136/DBI6f5cfTEEskChgWiux9hRqmMje5AAPfaXBgodv.xlsx",
        "file": "tmp/docs/cmt-136-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/136",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "137",
    "name": "State Owned Enterprises Committee's Sub-Committee 7 (To review the status of state-owned enterprises in the housing sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "256",
    "viceChairId": "260",
    "memberIds": [
      "258",
      "256",
      "260"
    ],
    "formerMemberIds": [
      "240"
    ],
    "meetingDates": [
      "18 Feb 2025",
      "11 Dec 2024",
      "21 Oct 2024",
      "30 Jul 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 7 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/137/sHZn5yOGLYuJPoBhiCYiBebcGaVLIVNRzw5oML7L.pdf",
        "file": "tmp/docs/cmt-137-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 7 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/137/JF8hS3BAgGjeg4UTcLXua4Eidvhr6I4miyVEgoXM.xlsx",
        "file": "tmp/docs/cmt-137-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/137",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "138",
    "name": "Housing Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "180",
    "viceChairId": "182",
    "memberIds": [
      "175",
      "180",
      "182",
      "185",
      "188",
      "191",
      "200",
      "229",
      "249",
      "195",
      "208"
    ],
    "formerMemberIds": [
      "214",
      "233"
    ],
    "meetingDates": [
      "10 Aug 2026",
      "14 Jul 2026",
      "29 Jun 2026",
      "17 Jun 2026",
      "15 Jun 2026"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance report of the Housing Committee until August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/138/RZo4wQO9iNRotwdEhttm1zAiKJq3uEOpV6mrB9ZP.pdf",
        "file": "tmp/docs/cmt-138-1.pdf"
      },
      {
        "label": "Attendance report of the Housing Committee until August 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/138/WwcA0N4YLQ0taYN6EN0Ya4h3p89XTatzJM2CLWxM.xlsx",
        "file": "tmp/docs/cmt-138-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/138",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "139",
    "name": "State Owned Enterprises Committee's Sub-Committee 1 (To review the status of state-owned enterprises in the trade and economy sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "239",
    "viceChairId": "230",
    "memberIds": [
      "253",
      "239",
      "230",
      "258"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "12 Aug 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 1 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/139/Fw2NIKsiGGO95Yh9TxjwtHWLcmTWBl5LndcTbDG0.pdf",
        "file": "tmp/docs/cmt-139-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 1 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/139/dKviHEU44FYRQfEfuWV0pjVUURBu0S35ogbIYDUz.xlsx",
        "file": "tmp/docs/cmt-139-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/139",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "140",
    "name": "Joint Committee of Committee on National Development And Heritage and Committee on Decentralization",
    "category": "Joint Committees",
    "status": "Completed",
    "chairId": "185",
    "viceChairId": "176",
    "memberIds": [
      "239",
      "185",
      "176",
      "178",
      "184",
      "192",
      "212",
      "216",
      "221",
      "226",
      "230",
      "238",
      "243",
      "245",
      "248",
      "250",
      "252",
      "255",
      "262",
      "265",
      "266",
      "267"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "18 Nov 2024",
      "13 Nov 2024",
      "21 Oct 2024",
      "15 Oct 2024",
      "22 Aug 2024"
    ],
    "works": 0,
    "documents": [],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/140",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "141",
    "name": "Committee of the Whole House",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "217",
    "viceChairId": "175",
    "memberIds": [
      "259",
      "217",
      "175",
      "176",
      "177",
      "178",
      "179",
      "180",
      "181",
      "182",
      "183",
      "184",
      "185",
      "186",
      "187",
      "188",
      "189",
      "190",
      "191",
      "192",
      "193",
      "194",
      "195",
      "196",
      "197",
      "198",
      "199",
      "200",
      "201",
      "202",
      "203",
      "204",
      "205",
      "206",
      "207",
      "208",
      "209",
      "210",
      "211",
      "212",
      "213",
      "214",
      "215",
      "216",
      "218",
      "219",
      "220",
      "221",
      "222",
      "223",
      "224",
      "225",
      "226",
      "227",
      "228",
      "229",
      "230",
      "231",
      "232",
      "234",
      "235",
      "236",
      "237",
      "238",
      "239",
      "240",
      "241",
      "242",
      "243",
      "244",
      "245",
      "246",
      "247",
      "248",
      "249",
      "250",
      "251",
      "252",
      "253",
      "254",
      "255",
      "256",
      "257",
      "258",
      "260",
      "261",
      "262",
      "263",
      "264",
      "265",
      "266",
      "267",
      "268"
    ],
    "formerMemberIds": [
      "233"
    ],
    "meetingDates": [
      "18 Aug 2026",
      "12 Aug 2026",
      "15 Jul 2026",
      "29 Jun 2026",
      "24 Nov 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance of Committee of the Whole House 2024",
        "url": "https://majlis.gov.mv/storage/committee_files/141/Ydnt2hACw63EqvJNmfpIos6zsbrUdIiiUVD92rEg.pdf",
        "file": "tmp/docs/cmt-141-1.pdf"
      },
      {
        "label": "Attendance of Committee of the Whole House 2025",
        "url": "https://majlis.gov.mv/storage/committee_files/141/un2gMCdLaXvzcUy61CAAqIJJI5t1ibg17o2GQvkk.pdf",
        "file": "tmp/docs/cmt-141-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/141",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "142",
    "name": "State Owned Enterprises Committee's Sub-Committee 5 (To review the status of state-owned enterprises in the tourism sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "258",
    "viceChairId": "230",
    "memberIds": [
      "247",
      "258",
      "230",
      "239"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "06 May 2025",
      "12 Mar 2025",
      "17 Feb 2025",
      "04 Nov 2024",
      "13 Aug 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 5 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/142/HcQb0P2IP4XjZBGVlwgdMHpv7eKmQYWiQSoRBWpn.pdf",
        "file": "tmp/docs/cmt-142-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 5 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/142/bBZtqYLin33FflUhhAsxeBvt2WCjccuaZuCNlqaz.xlsx",
        "file": "tmp/docs/cmt-142-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/142",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "143",
    "name": "State Owned Enterprises Committee's Sub-Committee 8 (To review the status of state-owned enterprises in the public service sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "247",
    "viceChairId": "230",
    "memberIds": [
      "239",
      "247",
      "230",
      "256"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "14 Aug 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 8 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/143/X2NVYAlKnkvOZByGWshCrHXoaSoxU03kjQFStcgO.pdf",
        "file": "tmp/docs/cmt-143-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 8 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/143/UL6bopMVWAk57RQNEbSVNB5LrFpFX6u1a8ZsJYFi.xlsx",
        "file": "tmp/docs/cmt-143-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/143",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "144",
    "name": "State Owned Enterprises Committee's Sub-Committee 2 (To review the status of state-owned enterprises in the fisheries sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "260",
    "viceChairId": "247",
    "memberIds": [
      "258",
      "260",
      "247",
      "257"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "18 Feb 2025",
      "03 Dec 2024",
      "04 Nov 2024",
      "19 Aug 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 2 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/144/FYghhr3KM5CYf1eRqNHcUPThE7EXr4UmlqloiDVC.pdf",
        "file": "tmp/docs/cmt-144-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 2 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/144/V1raipctPJJ7IsyqrWwXes7sAqcn1LQWOJ5sT3k2.xlsx",
        "file": "tmp/docs/cmt-144-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/144",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "145",
    "name": "State Owned Enterprises Committee's Sub-Committee 3 (To review the status of state-owned enterprises in the ports, airport, and airline sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "260",
    "viceChairId": "239",
    "memberIds": [
      "253",
      "260",
      "239",
      "256"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "10 Dec 2024",
      "09 Dec 2024",
      "26 Nov 2024",
      "25 Nov 2024",
      "29 Oct 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 3 of State Owned Enterprises Committee till September 2026 (20th Majlis",
        "url": "https://majlis.gov.mv/storage/committee_files/145/Kzolb0eiwjBepzQjvpjWToogC0EWJB5yYMd7HxI6.pdf",
        "file": "tmp/docs/cmt-145-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 3 of State Owned Enterprises Committee till September 2026 (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/145/l7C0Z6NTAjyixPZIInYvoJ2pnEIXv3FcXwH7QnVA.xlsx",
        "file": "tmp/docs/cmt-145-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/145",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "146",
    "name": "Budget Committee",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "249",
    "viceChairId": "177",
    "memberIds": [
      "217",
      "249",
      "177",
      "185",
      "196",
      "197",
      "203",
      "206",
      "207",
      "209",
      "222",
      "229",
      "231",
      "232",
      "240",
      "242",
      "252",
      "265",
      "266",
      "254",
      "258",
      "237"
    ],
    "formerMemberIds": [
      "192",
      "194",
      "218"
    ],
    "meetingDates": [
      "19 Nov 2025",
      "16 Nov 2025",
      "15 Nov 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Budget Committee for 2024 and 2025",
        "url": "https://majlis.gov.mv/storage/committee_files/146/8YJVT98A86xldnIfknU8VNfLqz3PNzEf8Sjb3MPG.xlsx",
        "file": "tmp/docs/cmt-146-1.pdf"
      },
      {
        "label": "Attendance Report of Budget Committee for 2024 and 2025",
        "url": "https://majlis.gov.mv/storage/committee_files/146/xw8qU9MJSgAn0ercdH3RD6xSUA4WxFT2zuJYb57d.pdf",
        "file": "tmp/docs/cmt-146-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/146",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "147",
    "name": "Joint Sub-Committee of Public Accounts Committee and Committee on Economic Affairs",
    "category": "Joint Committees",
    "status": "Completed",
    "chairId": "249",
    "viceChairId": "177",
    "memberIds": [
      "232",
      "249",
      "177",
      "185",
      "192",
      "194",
      "196",
      "197",
      "203",
      "206",
      "207",
      "209",
      "217",
      "218",
      "222",
      "229",
      "231",
      "240",
      "242",
      "252",
      "265",
      "266"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "28 Oct 2024",
      "27 Oct 2024"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Joint Committee of Public Accounts Committee and Committee on Economic Affairs",
        "url": "https://majlis.gov.mv/storage/committee_files/147/kjFhARzy0jzDhla4JcEmRRntEhcvtqdg4lBPgEk6.xlsx",
        "file": "tmp/docs/cmt-147-1.pdf"
      },
      {
        "label": "Attendance Report of Joint Committee of Public Accounts Committee and Committee on Economic Affairs",
        "url": "https://majlis.gov.mv/storage/committee_files/147/WzjuUm2uJRAmjpvri1YN1NFlKOyG6145I8RF8WRM.pdf",
        "file": "tmp/docs/cmt-147-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/147",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "149",
    "name": "Public Accounts Committee's Sub Committee - 02 (To review Special Audit of Police Housing Project)",
    "category": "Select Committees (Completed)",
    "status": "Completed",
    "chairId": "217",
    "viceChairId": "177",
    "memberIds": [
      "240",
      "217",
      "177",
      "206",
      "231"
    ],
    "formerMemberIds": [
      "178"
    ],
    "meetingDates": [
      "19 Nov 2025",
      "14 Oct 2025",
      "05 Aug 2025",
      "04 Aug 2025",
      "23 Jun 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 2 of Public Accounts Committee (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/149/Fa3EQ8WCxVptZjmPGwpyYX1emiiI4OrbM7tjtaWD.xlsx",
        "file": "tmp/docs/cmt-149-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 2 of Public Accounts Committee (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/149/zSTaHsybujqhdMl5kXwl888pNt4r7Pm8NGpLjgNF.pdf",
        "file": "tmp/docs/cmt-149-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/149",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "150",
    "name": "Select Committee on Bill on Amendment to the Tobacco Control Act (Law no.15/2010)",
    "category": "Select Committees",
    "status": "Completed",
    "chairId": "206",
    "viceChairId": "182",
    "memberIds": [
      "190",
      "206",
      "182",
      "209",
      "223",
      "247",
      "248"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "11 May 2025",
      "07 May 2025",
      "06 May 2025",
      "30 Apr 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "20th Ad Hoc Committee on Tobacco Control Act (Law no.15/2010) Amendment bill's attendance report",
        "url": "https://majlis.gov.mv/storage/committee_files/150/aXqWDFQ62TMKDFnVxqQQ8j7P5PTiysMYI5EiBLsP.pdf",
        "file": "tmp/docs/cmt-150-1.pdf"
      },
      {
        "label": "20th Ad Hoc Committee on Tobacco Control Act (Law no.15/2010) Amendment bill's attendance report",
        "url": "https://majlis.gov.mv/storage/committee_files/150/2gArk1JVRB4QLgVE8U5fAMRlTj0BrNEcg0lgJgNr.xlsx",
        "file": "tmp/docs/cmt-150-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/150",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "151",
    "name": "Joint Committee of Committee on National Development And Heritage and Committee on Social Affairs.",
    "category": "Joint Committees",
    "status": "Ongoing",
    "chairId": "190",
    "viceChairId": "176",
    "memberIds": [
      "194",
      "190",
      "176",
      "186",
      "188",
      "192",
      "205",
      "216",
      "221",
      "223",
      "226",
      "230",
      "245",
      "252",
      "255",
      "263",
      "264",
      "265",
      "182",
      "179",
      "206",
      "250"
    ],
    "formerMemberIds": [
      "184",
      "239",
      "248",
      "262",
      "218",
      "213"
    ],
    "meetingDates": [
      "11 Aug 2025",
      "15 Jul 2025",
      "14 Jul 2025",
      "01 Jul 2025"
    ],
    "works": 0,
    "documents": [],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/151",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "152",
    "name": "National Development and Heritage Committee's Sub-Committee - 1 (To review Annual Reports)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "230",
    "viceChairId": null,
    "memberIds": [
      "192",
      "230"
    ],
    "formerMemberIds": [
      "262"
    ],
    "meetingDates": [
      "07 Oct 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Committee on National Development and Heritage Sub Committee 1 - Attendance report Up to October 2025",
        "url": "https://majlis.gov.mv/storage/committee_files/152/hQ7yU01Z9jk1PELratphEhGuQyYJXqsF1j2G7xUN.xlsx",
        "file": "tmp/docs/cmt-152-1.pdf"
      },
      {
        "label": "Committee on National Development and Heritage Sub Committee 1 - Attendance report Up to October 2025",
        "url": "https://majlis.gov.mv/storage/committee_files/152/JSAo2Yvn2mv3hZnnT5EptrYB1tZMRZU2htlpL9gE.pdf",
        "file": "tmp/docs/cmt-152-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/152",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "153",
    "name": "Public Accounts Committee's Sub Committee - 03 (To review Special Audits of Fenaka Corporation Limited)",
    "category": "Select Committees (Completed)",
    "status": "Completed",
    "chairId": "206",
    "viceChairId": "177",
    "memberIds": [
      "217",
      "206",
      "177",
      "196",
      "231",
      "240"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "14 Jul 2026",
      "04 Mar 2026",
      "09 Nov 2025",
      "05 Nov 2025",
      "29 Oct 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Attendance Report of Sub-Committee 3 of Public Accounts Committee (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/153/ns6yKalO3xofNPemL4VieXAtEOIOFzwXIRltSlra.xlsx",
        "file": "tmp/docs/cmt-153-1.pdf"
      },
      {
        "label": "Attendance Report of Sub-Committee 3 of Public Accounts Committee (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/153/PhLxJqfAOJofI4o9AIxzB5KZQesKZV50W7hMngJz.pdf",
        "file": "tmp/docs/cmt-153-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/153",
    "fetchedAt": "2026-10-06"
  },
  {
    "id": "154",
    "name": "Select Committee on Bill on Amendment to the Decentralization Act (Law no.07/2010) and Bill on Amendment to the Local Council Election Act (Law no.10/2010)",
    "category": "Select Committees",
    "status": "Completed",
    "chairId": "185",
    "viceChairId": "206",
    "memberIds": [
      "194",
      "185",
      "206",
      "209",
      "216",
      "230",
      "245"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "26 Nov 2025",
      "24 Nov 2025",
      "19 Nov 2025"
    ],
    "works": 0,
    "documents": [
      {
        "label": "Ad Hoc Committee to review the Bill to Amend Act No. 10/2010 (Local Council Elections Act) and the Bill to Amend Act No. 7/2010 (Decentralization Act)’s attendance report (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/154/MwBXVSacjOVpcXm6HPUHIebkhiXcfI99wMKivNne.xlsx",
        "file": "tmp/docs/cmt-154-1.pdf"
      },
      {
        "label": "Ad Hoc Committee to review the Bill to Amend Act No. 10/2010 (Local Council Elections Act) and the Bill to Amend Act No. 7/2010 (Decentralization Act)’s attendance report (20th Majlis)",
        "url": "https://majlis.gov.mv/storage/committee_files/154/XhctuIh6FVS22g8srOELvx5kMD9FBPOteVIJ2NnZ.pdf",
        "file": "tmp/docs/cmt-154-2.pdf"
      }
    ],
    "url": "https://majlis.gov.mv/en/20-parliament/committee/154",
    "fetchedAt": "2026-10-06"
  }
]
