// AUTO-GENERATED by scripts/scrape_committees.py from majlis.gov.mv committee pages.
// Member IDs map directly to roster MP ids (mp-<id>).

export interface RealCommittee {
  id: string; name: string; category: string; status: 'Ongoing' | 'Completed'
  chairId: string | null; viceChairId: string | null
  memberIds: string[]; formerMemberIds: string[]
  meetingDates: string[]; works: number; url: string
}

export const REAL_COMMITTEES: RealCommittee[] = [
  {
    "id": "115",
    "name": "General Purpose Committee",
    "category": "Parliamentary work related Standing Committees",
    "status": "Ongoing",
    "chairId": "210",
    "viceChairId": "180",
    "memberIds": [
      "244",
      "210",
      "180",
      "211",
      "213",
      "216",
      "225",
      "239",
      "251",
      "255",
      "260"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "20 May 2026",
      "04 May 2026",
      "27 Apr 2026",
      "08 Mar 2026",
      "17 Feb 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/115"
  },
  {
    "id": "116",
    "name": "Petition Committee",
    "category": "Parliamentary work related Standing Committees",
    "status": "Ongoing",
    "chairId": "195",
    "viceChairId": "198",
    "memberIds": [
      "256",
      "195",
      "198",
      "199",
      "205",
      "212",
      "220",
      "261",
      "246",
      "231"
    ],
    "formerMemberIds": [
      "178",
      "233",
      "209"
    ],
    "meetingDates": [
      "12 May 2026",
      "04 May 2026",
      "22 Apr 2026",
      "26 Mar 2026",
      "11 Feb 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/116"
  },
  {
    "id": "117",
    "name": "Committee on Member’s Privileges and Ethics",
    "category": "Parliamentary work related Standing Committees",
    "status": "Ongoing",
    "chairId": "175",
    "viceChairId": "179",
    "memberIds": [
      "195",
      "175",
      "179",
      "202",
      "204",
      "215",
      "243",
      "253",
      "260",
      "261",
      "231"
    ],
    "formerMemberIds": [
      "191",
      "203"
    ],
    "meetingDates": [
      "06 May 2026",
      "15 Apr 2026",
      "11 Feb 2026",
      "11 Dec 2025",
      "03 Dec 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/117"
  },
  {
    "id": "118",
    "name": "Committee on Secondary Legislation",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "227",
    "viceChairId": "182",
    "memberIds": [
      "224",
      "227",
      "182",
      "193",
      "200",
      "208",
      "209",
      "210",
      "250",
      "255",
      "257"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "05 May 2026",
      "13 Apr 2026",
      "08 Mar 2026",
      "11 Feb 2026",
      "01 Dec 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/118"
  },
  {
    "id": "119",
    "name": "Public Accounts Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "217",
    "viceChairId": "177",
    "memberIds": [
      "232",
      "217",
      "177",
      "196",
      "197",
      "206",
      "231",
      "252",
      "266",
      "254",
      "185"
    ],
    "formerMemberIds": [
      "240",
      "178",
      "194"
    ],
    "meetingDates": [
      "14 May 2026",
      "26 Apr 2026",
      "22 Apr 2026",
      "21 Apr 2026",
      "11 Feb 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/119"
  },
  {
    "id": "120",
    "name": "Committee on Economic Affairs",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "265",
    "viceChairId": "185",
    "memberIds": [
      "249",
      "265",
      "185",
      "203",
      "207",
      "218",
      "229",
      "242",
      "222",
      "209",
      "258"
    ],
    "formerMemberIds": [
      "192",
      "246",
      "223",
      "199",
      "237",
      "239"
    ],
    "meetingDates": [
      "31 May 2026",
      "11 May 2026",
      "15 Apr 2026",
      "08 Mar 2026",
      "10 Feb 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/120"
  },
  {
    "id": "121",
    "name": "Committee on Social Affairs",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "190",
    "viceChairId": "186",
    "memberIds": [
      "188",
      "190",
      "186",
      "205",
      "221",
      "223",
      "226",
      "245",
      "263",
      "264",
      "182"
    ],
    "formerMemberIds": [
      "218",
      "213"
    ],
    "meetingDates": [
      "11 May 2026",
      "07 May 2026",
      "06 May 2026",
      "05 May 2026",
      "29 Apr 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/121"
  },
  {
    "id": "122",
    "name": "Committee on National Security Services (241)",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "214",
    "viceChairId": "187",
    "memberIds": [
      "217",
      "214",
      "187",
      "196",
      "197",
      "216",
      "231",
      "232",
      "234",
      "244",
      "246",
      "223",
      "252"
    ],
    "formerMemberIds": [
      "240",
      "222",
      "191"
    ],
    "meetingDates": [
      "06 May 2026",
      "21 Apr 2026",
      "27 Nov 2025",
      "08 Nov 2025",
      "06 Nov 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/122"
  },
  {
    "id": "123",
    "name": "Committee on Independent Institutions",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "196",
    "viceChairId": "181",
    "memberIds": [
      "225",
      "196",
      "181",
      "183",
      "187",
      "247",
      "267",
      "194",
      "195",
      "258"
    ],
    "formerMemberIds": [
      "224",
      "233",
      "236",
      "241",
      "206",
      "254",
      "179",
      "177"
    ],
    "meetingDates": [
      "12 May 2026",
      "11 May 2026",
      "27 Apr 2026",
      "30 Mar 2026",
      "16 Feb 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/123"
  },
  {
    "id": "124",
    "name": "Government Oversight Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "236",
    "viceChairId": "177",
    "memberIds": [
      "191",
      "236",
      "177",
      "183",
      "186",
      "193",
      "195",
      "246",
      "249",
      "235",
      "250"
    ],
    "formerMemberIds": [
      "181",
      "264"
    ],
    "meetingDates": [
      "13 May 2026",
      "27 Apr 2026",
      "11 Feb 2026",
      "27 Nov 2025",
      "22 Oct 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/124"
  },
  {
    "id": "125",
    "name": "Committee on National Development And Heritage",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "265",
    "viceChairId": "176",
    "memberIds": [
      "194",
      "265",
      "176",
      "184",
      "192",
      "216",
      "230",
      "252",
      "255",
      "262",
      "179"
    ],
    "formerMemberIds": [
      "239",
      "248"
    ],
    "meetingDates": [
      "06 May 2026",
      "27 Apr 2026",
      "05 Mar 2026",
      "17 Feb 2026",
      "10 Dec 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/125"
  },
  {
    "id": "126",
    "name": "Foreign Relations Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "200",
    "viceChairId": "184",
    "memberIds": [
      "228",
      "200",
      "184",
      "199",
      "207",
      "220",
      "237",
      "247",
      "254",
      "262",
      "189"
    ],
    "formerMemberIds": [
      "176"
    ],
    "meetingDates": [
      "01 Jun 2026",
      "14 May 2026",
      "29 Apr 2026",
      "21 Apr 2026",
      "13 Apr 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/126"
  },
  {
    "id": "127",
    "name": "Committee on Decentralization",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "250",
    "viceChairId": "178",
    "memberIds": [
      "185",
      "250",
      "178",
      "212",
      "221",
      "226",
      "238",
      "243",
      "245",
      "266",
      "267"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "13 May 2026",
      "12 May 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/127"
  },
  {
    "id": "128",
    "name": "Judiciary Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "206",
    "viceChairId": "218",
    "memberIds": [
      "210",
      "206",
      "218",
      "222",
      "229",
      "242",
      "251",
      "204",
      "244",
      "258",
      "250"
    ],
    "formerMemberIds": [
      "208",
      "227",
      "249",
      "224",
      "182",
      "215",
      "267",
      "199",
      "203"
    ],
    "meetingDates": [
      "11 May 2026",
      "21 Apr 2026",
      "24 Feb 2026",
      "17 Feb 2026",
      "11 Feb 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/128"
  },
  {
    "id": "129",
    "name": "Committee on Environment and Climate Change",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "241",
    "viceChairId": "190",
    "memberIds": [
      "189",
      "241",
      "190",
      "219",
      "228",
      "238",
      "250",
      "263",
      "266",
      "176",
      "240"
    ],
    "formerMemberIds": [
      "198",
      "206"
    ],
    "meetingDates": [
      "05 May 2026",
      "15 Apr 2026",
      "14 Apr 2026",
      "01 Dec 2025",
      "26 Nov 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/129"
  },
  {
    "id": "130",
    "name": "Committee on Human Rights and Gender",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "248",
    "viceChairId": "179",
    "memberIds": [
      "245",
      "248",
      "179",
      "199",
      "201",
      "227",
      "232",
      "254",
      "264",
      "189",
      "220"
    ],
    "formerMemberIds": [
      "213",
      "235",
      "256",
      "188",
      "206"
    ],
    "meetingDates": [
      "12 May 2026",
      "04 May 2026",
      "27 Apr 2026",
      "22 Apr 2026",
      "15 Apr 2026"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/130"
  },
  {
    "id": "131",
    "name": "Committee on State Owned Enterprises",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "247",
    "viceChairId": "187",
    "memberIds": [
      "239",
      "247",
      "187",
      "230",
      "240",
      "253",
      "256",
      "257",
      "258",
      "260",
      "193"
    ],
    "formerMemberIds": [
      "194"
    ],
    "meetingDates": [
      "05 May 2026",
      "27 Apr 2026",
      "10 Feb 2026",
      "25 Nov 2025",
      "18 Nov 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/131"
  },
  {
    "id": "132",
    "name": "Committee on Information and Communication Technology",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "184",
    "viceChairId": "175",
    "memberIds": [
      "204",
      "184",
      "175",
      "180",
      "201",
      "202",
      "211",
      "215",
      "219",
      "235",
      "237"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "05 May 2026",
      "22 Apr 2026",
      "14 Apr 2026",
      "11 Feb 2026",
      "26 Nov 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/132"
  },
  {
    "id": "133",
    "name": "Foreign Relations Sub Committee (To review Annual Reports)",
    "category": "Select Committees",
    "status": "Completed",
    "chairId": "247",
    "viceChairId": "184",
    "memberIds": [
      "228",
      "247",
      "184",
      "199",
      "200",
      "207",
      "237"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "13 Aug 2024",
      "06 Aug 2024",
      "30 Jul 2024",
      "09 Jul 2024",
      "11 Jun 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/133"
  },
  {
    "id": "134",
    "name": "Public Accounts Committee's Sub Committee - 01 (To review Audit Reports)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "196",
    "viceChairId": "197",
    "memberIds": [
      "206",
      "196",
      "197",
      "231",
      "266"
    ],
    "formerMemberIds": [
      "178"
    ],
    "meetingDates": [
      "13 Aug 2025",
      "12 Aug 2025",
      "17 Jun 2025",
      "30 Apr 2025",
      "19 Mar 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/134"
  },
  {
    "id": "135",
    "name": "State Owned Enterprises Committee's Sub-Committee 4 (To review the status of state-owned enterprises in the bank and finance sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "253",
    "viceChairId": "257",
    "memberIds": [
      "230",
      "253",
      "257",
      "258"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "22 Jul 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/135"
  },
  {
    "id": "136",
    "name": "State Owned Enterprises Committee's Sub-Committee 6 (To review the status of state-owned enterprises in the utilities sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "260",
    "viceChairId": "253",
    "memberIds": [
      "240",
      "260",
      "253",
      "256"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "27 Nov 2024",
      "30 Jul 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/136"
  },
  {
    "id": "137",
    "name": "State Owned Enterprises Committee's Sub-Committee 7 (To review the status of state-owned enterprises in the housing sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "256",
    "viceChairId": "240",
    "memberIds": [
      "258",
      "256",
      "240",
      "260"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "18 Feb 2025",
      "11 Dec 2024",
      "21 Oct 2024",
      "30 Jul 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/137"
  },
  {
    "id": "138",
    "name": "Housing Committee",
    "category": "State Institutions related Standing Committees",
    "status": "Ongoing",
    "chairId": "180",
    "viceChairId": "175",
    "memberIds": [
      "214",
      "180",
      "175",
      "182",
      "185",
      "188",
      "191",
      "200",
      "229",
      "249",
      "195"
    ],
    "formerMemberIds": [
      "233"
    ],
    "meetingDates": [
      "05 Nov 2025",
      "02 Nov 2025",
      "11 Aug 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/138"
  },
  {
    "id": "139",
    "name": "State Owned Enterprises Committee's Sub-Committee 1 (To review the status of state-owned enterprises in the trade and economy sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "239",
    "viceChairId": "230",
    "memberIds": [
      "253",
      "239",
      "230",
      "258"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "12 Aug 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/139"
  },
  {
    "id": "140",
    "name": "Joint Committee of Committee on National Development And Heritage and Committee on Decentralization",
    "category": "Joint Committees",
    "status": "Completed",
    "chairId": "185",
    "viceChairId": "176",
    "memberIds": [
      "239",
      "185",
      "176",
      "178",
      "184",
      "192",
      "212",
      "216",
      "221",
      "226",
      "230",
      "238",
      "243",
      "245",
      "248",
      "250",
      "252",
      "255",
      "262",
      "265",
      "266",
      "267"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "18 Nov 2024",
      "13 Nov 2024",
      "21 Oct 2024",
      "15 Oct 2024",
      "22 Aug 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/140"
  },
  {
    "id": "141",
    "name": "Committee of the Whole House",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "240",
    "viceChairId": "175",
    "memberIds": [
      "259",
      "240",
      "175",
      "176",
      "177",
      "178",
      "179",
      "180",
      "181",
      "182",
      "183",
      "184",
      "185",
      "186",
      "187",
      "188",
      "189",
      "190",
      "191",
      "192",
      "193",
      "194",
      "195",
      "196",
      "197",
      "198",
      "199",
      "200",
      "201",
      "202",
      "203",
      "204",
      "205",
      "206",
      "207",
      "208",
      "209",
      "210",
      "211",
      "212",
      "213",
      "214",
      "215",
      "216",
      "217",
      "218",
      "219",
      "220",
      "221",
      "222",
      "223",
      "224",
      "225",
      "226",
      "227",
      "228",
      "229",
      "230",
      "231",
      "232",
      "234",
      "235",
      "236",
      "237",
      "238",
      "239",
      "241",
      "242",
      "243",
      "244",
      "245",
      "246",
      "247",
      "248",
      "249",
      "250",
      "251",
      "252",
      "253",
      "254",
      "255",
      "256",
      "257",
      "258",
      "260",
      "261",
      "262",
      "263",
      "264",
      "265",
      "266",
      "267"
    ],
    "formerMemberIds": [
      "233"
    ],
    "meetingDates": [
      "24 Nov 2025",
      "04 Nov 2025",
      "20 Nov 2024",
      "12 Nov 2024",
      "30 Oct 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/141"
  },
  {
    "id": "142",
    "name": "State Owned Enterprises Committee's Sub-Committee 5 (To review the status of state-owned enterprises in the tourism sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "258",
    "viceChairId": "230",
    "memberIds": [
      "247",
      "258",
      "230",
      "239"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "06 May 2025",
      "12 Mar 2025",
      "17 Feb 2025",
      "04 Nov 2024",
      "13 Aug 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/142"
  },
  {
    "id": "143",
    "name": "State Owned Enterprises Committee's Sub-Committee 8 (To review the status of state-owned enterprises in the public service sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "247",
    "viceChairId": "230",
    "memberIds": [
      "239",
      "247",
      "230",
      "256"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "14 Aug 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/143"
  },
  {
    "id": "144",
    "name": "State Owned Enterprises Committee's Sub-Committee 2 (To review the status of state-owned enterprises in the fisheries sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "260",
    "viceChairId": "247",
    "memberIds": [
      "258",
      "260",
      "247",
      "257"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "18 Feb 2025",
      "03 Dec 2024",
      "04 Nov 2024",
      "19 Aug 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/144"
  },
  {
    "id": "145",
    "name": "State Owned Enterprises Committee's Sub-Committee 3 (To review the status of state-owned enterprises in the ports, airport, and airline sector)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "260",
    "viceChairId": "239",
    "memberIds": [
      "253",
      "260",
      "239",
      "256"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "10 Dec 2024",
      "09 Dec 2024",
      "26 Nov 2024",
      "25 Nov 2024",
      "29 Oct 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/145"
  },
  {
    "id": "146",
    "name": "Budget Committee",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "249",
    "viceChairId": "177",
    "memberIds": [
      "217",
      "249",
      "177",
      "185",
      "196",
      "197",
      "203",
      "206",
      "207",
      "209",
      "222",
      "229",
      "231",
      "232",
      "240",
      "242",
      "252",
      "265",
      "266",
      "254",
      "258",
      "237"
    ],
    "formerMemberIds": [
      "192",
      "194",
      "218"
    ],
    "meetingDates": [
      "19 Nov 2025",
      "16 Nov 2025",
      "15 Nov 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/146"
  },
  {
    "id": "147",
    "name": "Joint Sub-Committee of Public Accounts Committee and Committee on Economic Affairs",
    "category": "Joint Committees",
    "status": "Completed",
    "chairId": "249",
    "viceChairId": "177",
    "memberIds": [
      "232",
      "249",
      "177",
      "185",
      "192",
      "194",
      "196",
      "197",
      "203",
      "206",
      "207",
      "209",
      "217",
      "218",
      "222",
      "229",
      "231",
      "240",
      "242",
      "252",
      "265",
      "266"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "28 Oct 2024",
      "27 Oct 2024"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/147"
  },
  {
    "id": "149",
    "name": "Public Accounts Committee's Sub Committee - 02 (To review Special Audit of Police Housing Project)",
    "category": "Select Committees (Completed)",
    "status": "Completed",
    "chairId": "217",
    "viceChairId": "177",
    "memberIds": [
      "240",
      "217",
      "177",
      "206",
      "231"
    ],
    "formerMemberIds": [
      "178"
    ],
    "meetingDates": [
      "19 Nov 2025",
      "14 Oct 2025",
      "05 Aug 2025",
      "04 Aug 2025",
      "23 Jun 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/149"
  },
  {
    "id": "150",
    "name": "Select Committee on Bill on Amendment to the Tobacco Control Act (Law no.15/2010)",
    "category": "Select Committees",
    "status": "Completed",
    "chairId": "206",
    "viceChairId": "182",
    "memberIds": [
      "190",
      "206",
      "182",
      "209",
      "223",
      "247",
      "248"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "11 May 2025",
      "07 May 2025",
      "06 May 2025",
      "30 Apr 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/150"
  },
  {
    "id": "151",
    "name": "Joint Committee of Committee on National Development And Heritage and Committee on Social Affairs.",
    "category": "Joint Committees",
    "status": "Ongoing",
    "chairId": "190",
    "viceChairId": "176",
    "memberIds": [
      "194",
      "190",
      "176",
      "184",
      "186",
      "192",
      "205",
      "216",
      "221",
      "223",
      "226",
      "230",
      "245",
      "252",
      "255",
      "262",
      "263",
      "264",
      "265",
      "182",
      "179",
      "213"
    ],
    "formerMemberIds": [
      "188",
      "239",
      "248",
      "218"
    ],
    "meetingDates": [
      "11 Aug 2025",
      "15 Jul 2025",
      "14 Jul 2025",
      "01 Jul 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/151"
  },
  {
    "id": "152",
    "name": "National Development and Heritage Committee's Sub-Committee - 1 (To review Annual Reports)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "262",
    "viceChairId": "230",
    "memberIds": [
      "192",
      "262",
      "230"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "07 Oct 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/152"
  },
  {
    "id": "153",
    "name": "Public Accounts Committee's Sub Committee - 03 (To review Special Audits of Fenaka Corporation Limited)",
    "category": "Select Committees",
    "status": "Ongoing",
    "chairId": "177",
    "viceChairId": "177",
    "memberIds": [
      "206",
      "177",
      "196",
      "231"
    ],
    "formerMemberIds": [
      "240"
    ],
    "meetingDates": [
      "04 Mar 2026",
      "09 Nov 2025",
      "05 Nov 2025",
      "29 Oct 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/153"
  },
  {
    "id": "154",
    "name": "Select Committee on Bill on Amendment to the Decentralization Act (Law no.07/2010) and Bill on Amendment to the Local Council Election Act (Law no.10/2010)",
    "category": "Select Committees",
    "status": "Completed",
    "chairId": "185",
    "viceChairId": "206",
    "memberIds": [
      "194",
      "185",
      "206",
      "209",
      "216",
      "230",
      "245"
    ],
    "formerMemberIds": [],
    "meetingDates": [
      "26 Nov 2025",
      "24 Nov 2025",
      "19 Nov 2025"
    ],
    "works": 0,
    "url": "https://majlis.gov.mv/en/20-parliament/committee/154"
  }
]
